### PR TITLE
Update pulumi fork and patch

### PR DESCRIPTION
**Pull request by gitfool**
Updates pulumi fork and "dotnet recursion limit patch" to latest protocolbuffers:
* `main` is now the default branch (FWIW)
* `pulumi` branch is now off `3.20.x` branch (currently version `3.20.1`)

@mikhailshilkov PTAL

PS. this is obviously messy, so more than happy for you to close this pull request and sync the fork and re-apply the patch 😀

### CODE REVIEW

**Comment by gitfool** [comment]
@mikhailshilkov thoughts?

**Comment by mikhailshilkov** [comment]
Sorry for missing this! I agree we should sync and rebase instead - let me try this later today.

**Comment by mikhailshilkov** [comment]
Okay I think it's done - take a quick look? https://github.com/pulumi/protobuf/tree/pulumi

**Comment by gitfool** [comment]
@mikhailshilkov LGTM; assuming you're happy to patch off `main` rather than the `3.20.x` branch. I would sync upstream tags too.

**Comment by mikhailshilkov** [comment]
That's actually a good point, I rebased on 3.20.1 and pushed the tags.

**Comment by gitfool** [comment]
LGTM

**Comment by gitfool** [comment]
Would be nice to clean up the branches to match upstream too; i.e. have `3.20.x` and `main` as default instead of `master`, then delete all other branches.

**Comment by gitfool** [comment]
@mikhailshilkov make that a patch of the latest [Protocol Buffers v21.1](https://github.com/protocolbuffers/protobuf/releases/tag/v21.1) on the [21.x](https://github.com/protocolbuffers/protobuf/tree/21.x) branch. 😉

**Comment by AaronFriel** [comment]
@mikhailshilkov this looks like it's marked blocked - is .NET 6 the blocker?

**Comment by mikhailshilkov** [comment]
@AaronFriel  The code is actually all set - I'm keeping it open until the update is published to NuGet - the process had some issues, as you know. Alternatively, we can close this PR and open a separate issue.

**Comment by mikhailshilkov** [comment]
Okay it took me two months, sorry about that, but 3.20.1 is now published on NuGet. I'll close this PR.

**Comment by gitfool** [comment]
@mikhailshilkov good timing as I _really_ need to target dotnet 6.0 now that everything else is out of support.

Unless I'm missing something, I don't see your changes in this repo. Also, I hope we can keep this up to date more frequently, so I'm happy to submit pull requests if that helps.

**Comment by mikhailshilkov** [comment]
> Unless I'm missing something, I don't see your changes in this repo. 

It should be here: https://github.com/pulumi/protobuf/tree/pulumi

**Pull request closed without merging**
